---
  - name: update apt packages
    become: True
    shell: apt-get update
    ignore_errors: yes

  - name: install basic apt packages
    become: True
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - git
