---
  - name: update apt packages
    sudo: yes
    shell: apt-get update

  - name: install basic apt packages
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - git
      - npm
