---
  - name: update apt packages
    become: True
    apt: update_cache=yes cache_valid_time=3600

  - name: install nodejs requirements
    become: True
    apt: pkg={{ item }} state=present
    with_items:
      - python-software-properties
      - python
      - g++
      - make

  - name: add nodejs repo
    become: True
    shell: curl -sL https://deb.nodesource.com/setup_8.x | bash -

  - name: install nodejs
    become: True
    apt: pkg=nodejs

