---
  - name: update apt packages
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600

  - name: install nodejs requirements
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - python-software-properties
      - python 
      - g++ 
      - make 

  - name: install nodejs
    sudo: yes
    apt: pkg=nodejs
    
  - name: install n
    become: True
    shell: npm install -g n

  - name: upgrade nodejs
    command: sudo n latest
